dist: trusty
sudo: false
language: node_js
node_js: 7.10.0
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_1e2bbe134f98_key -iv $encrypted_1e2bbe134f98_iv
  -in client-secret.json.enc -out client-secret.json -d
- npm i -g npm@5.0.4
- npm i -g gulp-cli@1.3.0
# - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
# - export PATH="$HOME/.yarn/bin:$PATH"
# - yarn global add gulp-cli@1.3.0

script: npm run build

deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  target_branch: master
  local_dir: pages
  email: badersur@gmail.com
  name: Bader Nasser
  on: dev

- provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: bader-sur
  default: true
  verbosity: info
  on: dev
