language: node_js
node_js:
- 7.7.4

before_script:
- yarn global add gulp
script: gulp

deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  target_branch: master
  local_dir: dist
  email: badersur@gmail.com
  name: Bader Nasser
  on:
    branch: dev

- provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: badersur-push
  default: true
  on: dev

before_install:
- openssl aes-256-cbc -K $encrypted_1e2bbe134f98_key -iv $encrypted_1e2bbe134f98_iv
  -in client-secret.json.enc -out client-secret.json -d
