# Using Ubuntu 20.04
dist: focal
language: node_js
# latest stable Node.js release
node_js: node

branches:
  # safelist
  only:
    - dev

cache:
  directories:
    - node_modules
    - $HOME/.cache/yarn

#install:
#  # - rm yarn.lock
#  - yarn
#  - yarn upgrade --latest

script:
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    target_branch: master
    local_dir: public
    email: badersur@gmail.com
    name: Bader Nasser
    on:
      branch: dev
