dist: xenial
language: node_js

branches:
    # safelist
    only:
        - dev

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
    - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - rm yarn.lock
    - yarn

script:
    - yarn outdated || echo "Building!..."
    - yarn run build

deploy:
    -   provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        target_branch: master
        local_dir: public
        email: badersur@gmail.com
        name: Bader Nasser
        on:
            branch: dev
