dist: trusty
sudo: false
language: node_js

before_install:
- openssl aes-256-cbc -K $encrypted_1e2bbe134f98_key -iv $encrypted_1e2bbe134f98_iv
  -in client-secret.json.enc -out client-secret.json -d
# - if ! $(npm -v | grep -q '^6'); then npm i -g npm@6; fi
# - npm i -g npm@6
- npm i -g gulp-cli

script: npm run build

deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  target_branch: master
  local_dir: pages
  email: badersur@gmail.com
  name: Bader Nasser
  on: dev

- provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: bader-sur
  default: true
  verbosity: info
  on: dev
