# Credits: https://github.com/h5bp/server-configs-gae/blob/master/app.yaml

# see: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
# and https://jakearchibald.com/2016/caching-best-practices/
# for more info about caching

runtime: python27
api_version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  max_concurrent_requests: 16 # (Default: 8, Maximum: 80)
  max_idle_instances: automatic # default value
  max_pending_latency: automatic
  min_idle_instances: 1
  min_pending_latency: 30ms # default value

libraries:
- name: webapp2
  version: "2.5.2"

handlers:

# Manifest files

- url: /(.+\.webapp)
  upload: gae/(.+\.webapp)
  static_files: gae/\1
  mime_type: application/x-web-app-manifest+json
  expiration: "1s"
  secure: always

# Images (cached for a year since URLs contain hashes)

- url: /(.+\.ico)
  upload: gae/(.+\.ico)
  static_files: gae/\1
  expiration: "365d"
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"
    Content-Type: "image/x-icon"

- url: /(.+\.(gif|jpe?g|png|svgz?|webp))
  upload: gae/(.+\.(gif|jpe?g|png|svgz?|webp))
  static_files: gae/\1
  expiration: "365d"
  secure: always
  http_headers:
    # Allow cross-origin access to web fonts and images
    # You can also replace "*" with a specific host, e.g. https://example.org
    Access-Control-Allow-Origin: "*"

# CSS, Javascript, text and other file types

- url: /sw\.js
  upload: gae/sw\.js
  static_files: gae/sw.js
  expiration: "1s"
  secure: always
  http_headers:
    Content-Type: "text/javascript; charset=utf-8"

- url: /(.+\.js)
  upload: gae/(.+\.js)
  static_files: gae/\1
  expiration: "365d"
  secure: always
  http_headers:
    Content-Type: "text/javascript; charset=utf-8"

- url: /(.+\.css)
  upload: gae/(.+\.css)
  static_files: gae/\1
  expiration: "365d"
  secure: always
  http_headers:
    Content-Type: "text/css; charset=utf-8"

- url: /sitemap
  upload: gae/sitemap\.xml
  static_files: gae/sitemap.xml
  secure: always

- url: /manifest\.webmanifest
  upload: gae/manifest\.webmanifest
  static_files: gae/manifest.webmanifest
  secure: always
  http_headers:
    Content-Type: "application/manifest+json; charset=utf-8"

- url: /(.+\.(xml|txt|json|map))
  upload: gae/(.+\.(xml|txt|json|map))
  static_files: gae/\1
  secure: always

# HTML pages

- url: /(.+\.html)
  upload: gae/(.+\.html)
  static_files: gae/\1
  application_readable: true
  secure: always
  http_headers:
    # Force Internet Explorer to render pages in the highest available
    # mode in the various cases when it may not.
    # https://hsivonen.fi/doctype/#ie8
    X-UA-Compatible: "IE=edge"
    # For more details on how to craft a reasonable policy for your site, read:
    # http://www.html5rocks.com/en/tutorials/security/content-security-policy/ (or
    # the specification: http://www.w3.org/TR/CSP11/). Also, to make things easier,
    # you can use an online CSP header generator such as: http://cspisawesome.com/.
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"
    Content-Type: "text/html; charset=utf-8"

# Pretty links for courses & projects

- url: /((ar|en)/(courses|projects))/?
  upload: gae/(.+)\.html
  static_files: gae/\1.html
  application_readable: true
  secure: always
  http_headers:
    X-UA-Compatible: "IE=edge"
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"
    Content-Type: "text/html; charset=utf-8"

# Homepages for /ar/ & /en/

- url: /(ar|en)/?
  upload: gae/(.+)/index\.html
  static_files: gae/\1/index.html
  application_readable: true
  secure: always
  http_headers:
    X-UA-Compatible: "IE=edge"
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"
    Content-Type: "text/html; charset=utf-8"

# Redirecting & handling errors: 404 & 500

- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$

- ^client-secret\.json\.enc$
- ^gulpfile\.babel\.js$
- ^package\.json$
- ^package-lock\.json$
- ^README\.md$
- ^LICENSE$

- ^node_modules
- ^pages
- ^app
- ^\.tmp
- ^\.vscode
