# Credits: https://github.com/h5bp/server-configs-gae/blob/master/app.yaml

# see: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
# and https://jakearchibald.com/2016/caching-best-practices/
# for more info about caching

runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"

handlers:

# Manifest files

- url: /(.+\.webapp)
  static_files: gae/\1
  upload: gae/(.+\.webapp)
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"
  secure: always

# Images (cached for a year since URLs contain hashes)

- url: /(.+\.(gif|ico|jpe?g|png|svgz?|webp))
  static_files: gae/\1
  upload: gae/(.+\.(gif|ico|jpe?g|png|svgz?|webp))
  expiration: "365d"
  secure: always
  http_headers:
    # Allow cross-origin access to web fonts and images
    # You can also replace "*" with a specific host, e.g. https://example.org
    Access-Control-Allow-Origin: "*"

# CSS, Javascript, text and other file types

- url: /sw\.js
  static_files: gae/sw.js
  upload: gae/sw\.js
  expiration: "0s"
  secure: always

- url: /(.+\.(css|js))
  static_files: gae/\1
  upload: gae/(.+\.(css|js))
  expiration: "365d"
  secure: always

- url: /(.+\.(xml|txt|json|map))
  static_files: gae/\1
  upload: gae/(.+\.(xml|txt|json|map))
  expiration: "10m"
  secure: always

# HTML pages

- url: /(.+\.html)
  static_files: gae/\1
  upload: gae/(.+\.html)
  application_readable: true
  expiration: "5m"
  secure: always
  http_headers:
    # Force Internet Explorer to render pages in the highest available
    # mode in the various cases when it may not.
    # https://hsivonen.fi/doctype/#ie8
    X-UA-Compatible: "IE=edge"
    # For more details on how to craft a reasonable policy for your site, read:
    # http://www.html5rocks.com/en/tutorials/security/content-security-policy/ (or
    # the specification: http://www.w3.org/TR/CSP11/). Also, to make things easier,
    # you can use an online CSP header generator such as: http://cspisawesome.com/.
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"

# Pretty links for courses & projects

- url: /(courses|projects)
  static_files: gae/\1.html
  upload: gae/(.+)\.html
  application_readable: true
  expiration: "5m"
  secure: always
  http_headers:
    X-UA-Compatible: "IE=edge"
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"

# Homepage

- url: /
  static_files: gae/index.html
  upload: gae/index\.html
  application_readable: true
  expiration: "5m"
  secure: always
  http_headers:
    X-UA-Compatible: "IE=edge"
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"

# 404 & 500

- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^pages/.*
- ^\.tmp/.*
- ^\.publish/.*
