# Credits: https://github.com/h5bp/server-configs-gae/blob/master/app.yaml

runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

libraries:
- name: webapp2
  version: "2.5.2"

handlers:

# Manifest files

- url: /(.+\.(appcache))
  static_files: dist/\1
  upload: dist/(.+\.(appcache))
  mime_type: text/cache-manifest
  expiration: "0s"
  secure: always

- url: /(.+\.webapp)
  static_files: dist/\1
  upload: dist/(.+\.webapp)
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"
  secure: always

# Fonts and images

- url: /(.+\.(eot|otf|tt[cf]|woff2?|cur|gif|ico|jpe?g|png|svgz?|webp))
  static_files: dist/\1
  upload: dist/(.+\.(eot|otf|tt[cf]|woff2?|cur|gif|ico|jpe?g|png|svgz?|webp))
  secure: always
  http_headers:
    # Allow cross-origin access to web fonts and images
    # You can also replace "*" with a specific host, e.g. https://example.org
    Access-Control-Allow-Origin: "*"

# CSS, Javascript, text and other file types

- url: /(.+\.(css|js|xml|txt|json|map))
  static_files: dist/\1
  upload: dist/(.+\.(css|js|xml|txt|json|map))
  expiration: "10m"
  secure: always

# HTML pages

- url: /(.+\.html)
  static_files: dist/\1
  upload: dist/(.+\.html)
  application_readable: true
  expiration: "10m"
  secure: always
  http_headers:
    # Force Internet Explorer to render pages in the highest available
    # mode in the various cases when it may not.
    # https://hsivonen.fi/doctype/#ie8
    X-UA-Compatible: "IE=edge"
    # For more details on how to craft a reasonable policy for your site, read:
    # http://www.html5rocks.com/en/tutorials/security/content-security-policy/ (or
    # the specification: http://www.w3.org/TR/CSP11/). Also, to make things easier,
    # you can use an online CSP header generator such as: http://cspisawesome.com/.
    # Content-Security-Policy: "script-src 'self'; object-src 'self'"

# Homepage, 404 & 500

- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?bower\.json
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^(.*/)?tests/.*
- ^.*.md|markdown
